### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by brandly** [nickb1080/nba#19]
I know [you're aware of it](https://github.com/nickb1080/nba#re-this-readme), but I figured I'd open the issue.

One thing I think would be nice is including an example of the options under [a method](https://github.com/nickb1080/nba#playerprofile), so you can see how to call the method, but also click the URL to view an actual response.

Most of my use has been reading [stats-endpoints](https://github.com/nickb1080/nba/blob/master/src/stats-endpoints.js), and then logging out responses to see what data I'm working with. If you're open to it, I could follow this workflow and write some docs. Let me know what you think!

**Comment by nickb1080** [comment]
Sure thing, documentation contributions would be very welcome! I haven't had time to take a proper stab at it. The best place to start is with the integration tests actually, since there is a working example call for each method.

Next, if you create a directory called `responses` in the root of your clone, each of the stats methods tests will save a json file there with the full response body, which is handy to refer to. (Run `npm test` or `make test` in the root of the project). Finally, I just added a file called `test/interactive.js`. If  you run it with `node test/interactive.js`, it'll run the tests but then attach a Node [REPL](https://nodejs.org/api/repl.html) where the responses are available so you can interactively play around with their shape. You can find the data by `StatsData[methodName]` or `SportVuData[methodName]`

**Comment by nickb1080** [comment]
Upcoming version 3 of this library will have some decent documentation.

**Comment by brandly** [comment]
Excited for the new version! Excited for the new NBA season!!

**Comment by nickb1080** [comment]
several new endpoints are added in the `v3` branch, plus various other improvements
https://github.com/nickb1080/nba/tree/v3

**Comment by nickb1080** [comment]
@brandly v3 is out! There are some autogenerated [docs](https://github.com/nickb1080/nba/blob/master/doc/stats.md) showing what parameters are accepted for the `stats` namespace. I'm working on better documentation for the other namespaces, as well as automatically generating docs the "shape" of each API response.

**Comment by arjunblj** [comment]
This is awesome @nickb1080 -- thanks!

**Comment by brandly** [comment]
great work @nickb1080! i've got an old version running in a chat bot, so i'll have to update soon
