### ISSUE TITLE
Angular implementation

### ISSUE THREAD

**Issue by orochamartins** [nickb1080/nba#34]
Sorry to open an issue but i've been trying for days using this API in an AngularJs Exercise.

Im trying to use $http to GET the result of something, but when i try, i get all kind of Forbidden/Denied access to the data.

For example:

```
var app = angular.module('app',[]);

app.controller('myCtrl', function($http){
	var self = this;

	$http.get(http://stats.nba.com/stats/teamdashboardbygeneralsplits')
	.then(function(response) {
            self.stats = response.data;
        });
});
```

Is this the right way to do it or im completely off? Or do i have to use $resourceProvider?

Error examples:

`GET http://stats.nba.com/stats/teamdashboardbygeneralsplits 400 (Bad Request)`

`XMLHttpRequest cannot load http://stats.nba.com/stats/teamdashboardbygeneralsplits. No 'Access-Control-Allow-Origin' header is present on the requested resource. The response had HTTP status code 400.`

Thanks in advance.

**Comment by nickb1080** [comment]
You're running into a browser issue with [cross origin resource sharing](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS). In general, you won't be able to access the NBA's API endpoints from your browser directly, because the NBA doesn't provide `Access-Control-Allow-Origin: *` on their responses. You will need to set up a server of your own, that you call from your Angular app, which in turn calls nba.com.

Something like the following in an express app:

```
var nba = require("nba");
app.use("/dashboard", function (req, res, next) {
  nba.stats.teamSplits()
    .then(function (resp) {
      res.json(resp);
    })
    .catch(next);
});
```

Then point your Angular `$http.get()` at your app
